"""Generate Pydantic models from the JSON Schema.

Usage:
    uv run scripts/json2pydantic.py <output_path>

Reads:
    build/schema/schema.json
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from datamodel_code_generator import (
    GenerateConfig,
    InputFileType,
    ModuleSplitMode,
    PythonVersion,
    ReuseScope,
    TargetPydanticVersion,
    generate,
)
from datamodel_code_generator.enums import (
    DataModelType,
)

_PROJECT_ROOT = Path(__file__).parent.parent
_SCHEMA_PATH = _PROJECT_ROOT / "build" / "schema" / "schema.json"
_VERSION_PATH = _PROJECT_ROOT / "build" / "schema" / "version.txt"
_GENERATOR_COMMENT_RE = re.compile(
    r"^# generated by datamodel-codegen:.*?(?=\nfrom|\nclass|\Z)",
    re.DOTALL | re.MULTILINE,
)


def _generate(output: Path) -> None:
    if not _SCHEMA_PATH.exists():
        print(f"Error: schema not found at {_SCHEMA_PATH}", file=sys.stderr)
        sys.exit(1)

    output.parent.mkdir(parents=True, exist_ok=True)

    config = GenerateConfig(
        base_class="pydantic.BaseModel",
        collapse_reuse_models=True,
        collapse_root_models=True,
        formatters=[],
        input_file_type=InputFileType.JsonSchema,
        keep_model_order=True,
        output_model_type=DataModelType.PydanticV2BaseModel,
        output=output,
        reuse_model=True,
        reuse_scope=ReuseScope.Tree,
        snake_case_field=True,
        target_pydantic_version=TargetPydanticVersion.V2_11,
        target_python_version=PythonVersion.PY_314,
        module_split_mode=ModuleSplitMode.Single,
    )

    generate(_SCHEMA_PATH, config=config)
    print(f"Models written to {output}")


def main() -> None:
    """Entry point."""
    parser = argparse.ArgumentParser(
        description="Generate Pydantic models from the JSON Schema."
    )
    parser.add_argument(
        "output",
        type=Path,
        help="Output path for the generated .py file",
    )
    args = parser.parse_args()
    _generate(args.output)


if __name__ == "__main__":
    main()
